import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { supabase } from "@/lib/supabaseClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}> 
        <div className="min-h-screen flex flex-col">
          {/* Header */}
          <header className="bg-blue-600 text-white h-12 flex items-center px-6 font-semibold text-lg shadow-sm fixed top-0 left-0 w-full z-30">
            wall
          </header>
          <div className="flex flex-1 pt-12">
            {/* Sidebar */}
            <aside className="hidden md:flex flex-col w-72 bg-white border-r border-gray-200 p-6 gap-6 fixed h-full top-12 left-0 z-20 overflow-y-auto">
              <div className="flex flex-col items-center">
                <Image
                  src="/profile.jpg"
                  alt="James Neo Culala"
                  width={320}
                  height={320}
                  className="rounded-lg object-cover mb-4"
                />
                <div className="text-xl font-bold">James Neo Culala</div>
                <div className="text-gray-500 text-sm mb-2">wall</div>
                <button className="border rounded px-3 py-1 text-sm mt-2">Information</button>
              </div>
              <div>
                <div className="text-xs text-gray-400 uppercase mb-1">Networks</div>
                <div className="text-sm">Stanford Alum</div>
              </div>
              <div>
                <div className="text-xs text-gray-400 uppercase mb-1">Current City</div>
                <div className="text-sm">San Jose City, Nueva Ecija, PH</div>
              </div>
            </aside>
            {/* Main Content */}
            <main className="flex-1 bg-gray-50 min-h-screen flex flex-col items-center py-8 px-2 md:px-0 md:ml-72">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
